import os

DEFAULT_RESPONSE_MODEL = os.getenv("OPENAI_WRAPPER_DEFAULT_RESPONSE_MODEL", "gpt-5.2")
DEFAULT_EMBEDDING_MODEL = os.getenv("OPENAI_WRAPPER_DEFAULT_EMBEDDING_MODEL", "text-embedding-3-small")
DEFAULT_TIMEOUT_SECONDS = float(os.getenv("OPENAI_WRAPPER_TIMEOUT_SECONDS", "60"))
